\echo Applying ordered migrations from /docker-entrypoint-initdb.d/migrations
\i /docker-entrypoint-initdb.d/migrations/V1__init_schema.sql
\i /docker-entrypoint-initdb.d/migrations/V2__seed_data.sql
\i /docker-entrypoint-initdb.d/migrations/V3__convert_enums_to_varchar.sql
\i /docker-entrypoint-initdb.d/migrations/V4__notification_reminder_document_tracking.sql
\i /docker-entrypoint-initdb.d/migrations/V5__add_validator_last_seen_pending_at.sql
\i /docker-entrypoint-initdb.d/migrations/V6__seed_italian_business_categories.sql
\i /docker-entrypoint-initdb.d/migrations/V7__localize_and_reset_categories_to_ateco_sections.sql
\i /docker-entrypoint-initdb.d/migrations/V8__add_supplier_preferred_language.sql
\i /docker-entrypoint-initdb.d/migrations/V9__create_revamp_v2_core_tables.sql
\i /docker-entrypoint-initdb.d/migrations/V10__create_revamp_final_name_compat_views.sql
\i /docker-entrypoint-initdb.d/migrations/V11__materialize_final_table_names_with_revamp_compat_views.sql
\i /docker-entrypoint-initdb.d/migrations/V12__rename_revamp_db_objects_to_final_names.sql
\i /docker-entrypoint-initdb.d/migrations/V13__normalize_validator_role_to_admin.sql
\i /docker-entrypoint-initdb.d/migrations/V14__rename_validator_last_seen_column_to_admin.sql
\i /docker-entrypoint-initdb.d/migrations/V15__retire_legacy_user_role_enum_artifacts.sql
\i /docker-entrypoint-initdb.d/migrations/V15__add_user_soft_delete.sql
\i /docker-entrypoint-initdb.d/migrations/V16__enforce_single_admin_governance_role.sql
\i /docker-entrypoint-initdb.d/migrations/V17__phase7_json_key_backfill_and_attachment_profile_detail.sql
\i /docker-entrypoint-initdb.d/migrations/V18__add_review_case_verification_fields.sql
\i /docker-entrypoint-initdb.d/migrations/V19__add_review_case_verification_outcome.sql
\i /docker-entrypoint-initdb.d/migrations/V20__ensure_review_case_status_allows_ready_for_decision.sql
\i /docker-entrypoint-initdb.d/migrations/V21__replace_legacy_revamp_review_case_status_constraint.sql
\i /docker-entrypoint-initdb.d/migrations/V22__add_supplier_evaluator_assignments.sql
\i /docker-entrypoint-initdb.d/migrations/V23__extend_supplier_evaluator_assignments_lifecycle.sql
\i /docker-entrypoint-initdb.d/migrations/V24__add_revamp_application_identity_uniqueness.sql
\i /docker-entrypoint-initdb.d/migrations/V25__add_user_email_verified.sql
\i /docker-entrypoint-initdb.d/migrations/V26__make_full_name_nullable.sql
\i /docker-entrypoint-initdb.d/migrations/V27__make_supplier_profile_registration_columns_nullable.sql
\i /docker-entrypoint-initdb.d/migrations/V28__replace_admin_seed_users.sql
\i /docker-entrypoint-initdb.d/migrations/V29__rework_evaluation_system.sql
